// Command gendict rebuilds zhconv t2s tables from upstream OpenCC dictionaries.
//
// Usage:
//
//	go run ./scripts/gendict
//	go run ./scripts/gendict -ref=master -out-root=.
//
// Environment:
//
//	OPENCC_REF  default git ref when -ref is empty (default: master)
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
	"unicode/utf8"
)

const (
	defaultRepo = "BYVoid/OpenCC"
	defaultRef  = "master"
	userAgent   = "zhconv-go-gendict/1.0 (+https://github.com/xylplm/zhconv-go)"

	// Soft floor against accidental empty / truncated upstream dumps.
	minChars   = 1000
	minPhrases = 200
)

// Upstream OpenCC dictionary paths used to build unidirectional t2s tables.
var sourceFiles = []string{
	"data/dictionary/TSCharacters.txt",
	"data/dictionary/TSPhrases.txt",
	"data/dictionary/TWPhrasesRev.txt",
	"data/dictionary/TWVariants.txt",
	"data/dictionary/HKVariants.txt",
}

type mapping struct {
	from string
	to   string
}

type sourceMeta struct {
	Repo        string            `json:"repo"`
	Ref         string            `json:"ref"`
	Commit      string            `json:"commit"`
	CommitURL   string            `json:"commit_url"`
	GeneratedAt string            `json:"generated_at"`
	Files       map[string]string `json:"files_sha256_prefix"`
	Counts      map[string]int    `json:"counts"`
	Notes       []string          `json:"notes"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gendict: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	refFlag := flag.String("ref", "", "OpenCC git ref (tag/branch/sha); default OPENCC_REF or master")
	repo := flag.String("repo", defaultRepo, "OpenCC GitHub repo owner/name")
	outRoot := flag.String("out-root", ".", "repository root to write dict/ and table/")
	timeout := flag.Duration("timeout", 60*time.Second, "HTTP timeout for each request")
	retries := flag.Int("retries", 3, "HTTP retries for transient failures")
	flag.Parse()

	ref := strings.TrimSpace(*refFlag)
	if ref == "" {
		ref = strings.TrimSpace(os.Getenv("OPENCC_REF"))
	}
	if ref == "" {
		ref = defaultRef
	}
	if *retries < 1 {
		*retries = 1
	}

	client := &http.Client{Timeout: *timeout}
	commit, err := resolveCommit(client, *repo, ref, *retries)
	if err != nil {
		return err
	}
	fmt.Printf("OpenCC %s@%s -> %s\n", *repo, ref, shortSHA(commit))

	raw := make(map[string][]byte, len(sourceFiles))
	filePrefix := make(map[string]string, len(sourceFiles))
	for _, path := range sourceFiles {
		body, err := fetchRaw(client, *repo, commit, path, *retries)
		if err != nil {
			return err
		}
		raw[path] = body
		filePrefix[filepath.Base(path)] = fmt.Sprintf("%x", sha256Prefix(body, 8))
		fmt.Printf("  fetched %s (%d bytes)\n", path, len(body))
	}

	chars, phrases, err := buildTables(raw)
	if err != nil {
		return err
	}
	if len(chars) < minChars {
		return fmt.Errorf("chars too few: %d (min %d); abort to avoid bad publish", len(chars), minChars)
	}
	if len(phrases) < minPhrases {
		return fmt.Errorf("phrases too few: %d (min %d); abort to avoid bad publish", len(phrases), minPhrases)
	}
	fmt.Printf("  generated chars=%d phrases=%d\n", len(chars), len(phrases))

	header := []string{
		"# traditional\tsimplified",
		"# Generated by scripts/gendict from OpenCC (Apache-2.0).",
		"# Do not edit by hand; run: go run ./scripts/gendict",
		fmt.Sprintf("# source: https://github.com/%s/commit/%s", *repo, commit),
	}

	charTSV := renderTSV(header, chars)
	phraseTSV := renderTSV(header, phrases)

	targets := []string{
		filepath.Join(*outRoot, "dict"),
		filepath.Join(*outRoot, "table"),
	}
	for _, dir := range targets {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		if err := atomicWriteFile(filepath.Join(dir, "chars.tsv"), charTSV, 0o644); err != nil {
			return err
		}
		if err := atomicWriteFile(filepath.Join(dir, "phrases.tsv"), phraseTSV, 0o644); err != nil {
			return err
		}
	}

	meta := sourceMeta{
		Repo:        *repo,
		Ref:         ref,
		Commit:      commit,
		CommitURL:   fmt.Sprintf("https://github.com/%s/commit/%s", *repo, commit),
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Files:       filePrefix,
		Counts: map[string]int{
			"chars":   len(chars),
			"phrases": len(phrases),
		},
		Notes: []string{
			"TSCharacters is the primary character map (first candidate kept).",
			"TWVariants/HKVariants are reversed to cover regional glyphs; existing TSCharacters entries win.",
			"TSPhrases then TWPhrasesRev; later phrase keys overwrite earlier ones.",
			"Phrase targets may still contain traditional glyphs; runtime normalizes with the character map.",
		},
	}
	if err := writeJSON(filepath.Join(*outRoot, "dict", "SOURCE.json"), meta); err != nil {
		return err
	}
	if err := writeNOTICE(filepath.Join(*outRoot, "dict", "NOTICE"), meta); err != nil {
		return err
	}

	// Parity check before declaring success.
	for _, name := range []string{"chars.tsv", "phrases.tsv"} {
		a, err := os.ReadFile(filepath.Join(*outRoot, "dict", name))
		if err != nil {
			return err
		}
		b, err := os.ReadFile(filepath.Join(*outRoot, "table", name))
		if err != nil {
			return err
		}
		if !bytes.Equal(a, b) {
			return fmt.Errorf("dict/%s and table/%s diverge after write", name, name)
		}
	}

	fmt.Println("wrote dict/ and table/ characters + phrases")
	return nil
}

func buildTables(raw map[string][]byte) (chars, phrases []mapping, err error) {
	tsChars, err := parseOpenCCDict(raw["data/dictionary/TSCharacters.txt"])
	if err != nil {
		return nil, nil, fmt.Errorf("TSCharacters: %w", err)
	}
	tsPhrases, err := parseOpenCCDict(raw["data/dictionary/TSPhrases.txt"])
	if err != nil {
		return nil, nil, fmt.Errorf("TSPhrases: %w", err)
	}
	twPhrases, err := parseOpenCCDict(raw["data/dictionary/TWPhrasesRev.txt"])
	if err != nil {
		return nil, nil, fmt.Errorf("TWPhrasesRev: %w", err)
	}
	twVariants, err := parseOpenCCDict(raw["data/dictionary/TWVariants.txt"])
	if err != nil {
		return nil, nil, fmt.Errorf("TWVariants: %w", err)
	}
	hkVariants, err := parseOpenCCDict(raw["data/dictionary/HKVariants.txt"])
	if err != nil {
		return nil, nil, fmt.Errorf("HKVariants: %w", err)
	}

	// Character map: TS first, then reverse regional variants into gaps only.
	charMap := make(map[string]string, len(tsChars)+256)
	for _, m := range tsChars {
		if !isSingleRune(m.from) {
			continue
		}
		if m.from == m.to {
			continue
		}
		charMap[m.from] = m.to
	}
	applyReversedVariants(charMap, twVariants)
	applyReversedVariants(charMap, hkVariants)

	// Phrases: base t2s first, Taiwan reverse phrases overwrite same keys.
	phraseMap := make(map[string]string, len(tsPhrases)+len(twPhrases))
	for _, m := range tsPhrases {
		if m.from == "" || m.from == m.to {
			continue
		}
		phraseMap[m.from] = m.to
	}
	for _, m := range twPhrases {
		if m.from == "" || m.from == m.to {
			continue
		}
		phraseMap[m.from] = m.to
	}
	// Multi-rune character sources spilled above can also live as phrases if present in TS.
	for _, m := range tsChars {
		if isSingleRune(m.from) || m.from == "" || m.from == m.to {
			continue
		}
		if _, ok := phraseMap[m.from]; !ok {
			phraseMap[m.from] = m.to
		}
	}

	chars = mapToSorted(charMap)
	phrases = mapToSorted(phraseMap)
	return chars, phrases, nil
}

// applyReversedVariants maps regional glyphs back toward simplified.
// OpenCC stores base→regional; we reverse regional→simplified(base).
// Existing TSCharacters entries are never overwritten.
func applyReversedVariants(charMap map[string]string, variants []mapping) {
	for _, m := range variants {
		base := m.from
		regional := m.to
		if !isSingleRune(base) || !isSingleRune(regional) {
			continue
		}
		if regional == "" || regional == base {
			continue
		}
		if _, exists := charMap[regional]; exists {
			continue
		}
		simplified := base
		if s, ok := charMap[base]; ok {
			simplified = s
		}
		if regional == simplified {
			continue
		}
		charMap[regional] = simplified
	}
}

func parseOpenCCDict(data []byte) ([]mapping, error) {
	if len(data) == 0 {
		return nil, fmt.Errorf("empty dictionary")
	}
	out := make([]mapping, 0, 1024)
	sc := bufio.NewScanner(bytes.NewReader(data))
	// OpenCC lines are short; still allow long phrase lines.
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		tab := strings.IndexByte(line, '\t')
		if tab < 0 {
			return nil, fmt.Errorf("line %d: missing tab", lineNo)
		}
		from := strings.TrimSpace(line[:tab])
		rest := strings.TrimSpace(line[tab+1:])
		if from == "" || rest == "" {
			continue
		}
		// First candidate only (OpenCC multi-value separated by spaces).
		to := rest
		if i := strings.IndexByte(rest, ' '); i >= 0 {
			to = rest[:i]
		}
		to = strings.TrimSpace(to)
		if to == "" || from == to {
			continue
		}
		if !utf8.ValidString(from) || !utf8.ValidString(to) {
			return nil, fmt.Errorf("line %d: invalid utf-8", lineNo)
		}
		out = append(out, mapping{from: from, to: to})
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func mapToSorted(m map[string]string) []mapping {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := make([]mapping, 0, len(keys))
	for _, k := range keys {
		out = append(out, mapping{from: k, to: m[k]})
	}
	return out
}

func renderTSV(header []string, ms []mapping) []byte {
	var b strings.Builder
	// Rough pre-size: headers + ~8 bytes per entry average lower bound.
	b.Grow(len(header)*64 + len(ms)*12)
	for _, h := range header {
		b.WriteString(h)
		b.WriteByte('\n')
	}
	for _, m := range ms {
		b.WriteString(m.from)
		b.WriteByte('\t')
		b.WriteString(m.to)
		b.WriteByte('\n')
	}
	return []byte(b.String())
}

func isSingleRune(s string) bool {
	if s == "" {
		return false
	}
	_, size := utf8.DecodeRuneInString(s)
	return size == len(s) && size > 0
}

func resolveCommit(client *http.Client, repo, ref string, retries int) (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/commits/%s", repo, ref)
	body, err := httpGet(client, url, "application/vnd.github+json", retries)
	if err != nil {
		return "", fmt.Errorf("resolve commit %s@%s: %w", repo, ref, err)
	}
	var payload struct {
		SHA string `json:"sha"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		return "", err
	}
	if payload.SHA == "" {
		return "", fmt.Errorf("empty commit sha for %s@%s", repo, ref)
	}
	return payload.SHA, nil
}

func fetchRaw(client *http.Client, repo, commit, path string, retries int) ([]byte, error) {
	url := fmt.Sprintf("https://raw.githubusercontent.com/%s/%s/%s", repo, commit, path)
	body, err := httpGet(client, url, "", retries)
	if err != nil {
		return nil, fmt.Errorf("fetch %s: %w", path, err)
	}
	if len(body) == 0 {
		return nil, fmt.Errorf("fetch %s: empty body", path)
	}
	return body, nil
}

func httpGet(client *http.Client, url, accept string, retries int) ([]byte, error) {
	var last error
	for attempt := 1; attempt <= retries; attempt++ {
		req, err := http.NewRequest(http.MethodGet, url, nil)
		if err != nil {
			return nil, err
		}
		req.Header.Set("User-Agent", userAgent)
		if accept != "" {
			req.Header.Set("Accept", accept)
		}
		resp, err := client.Do(req)
		if err != nil {
			last = err
			sleepBackoff(attempt)
			continue
		}
		body, readErr := io.ReadAll(io.LimitReader(resp.Body, 8<<20))
		_ = resp.Body.Close()
		if readErr != nil {
			last = readErr
			sleepBackoff(attempt)
			continue
		}
		// Retry rate-limit / transient 5xx.
		if resp.StatusCode == http.StatusTooManyRequests || resp.StatusCode >= 500 {
			last = fmt.Errorf("HTTP %d: %s", resp.StatusCode, truncate(string(body), 200))
			sleepBackoff(attempt)
			continue
		}
		if resp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, truncate(string(body), 200))
		}
		return body, nil
	}
	if last == nil {
		last = fmt.Errorf("exhausted %d retries", retries)
	}
	return nil, last
}

func sleepBackoff(attempt int) {
	// 200ms, 400ms, 800ms... capped roughly by attempt count.
	d := time.Duration(200*(1<<(attempt-1))) * time.Millisecond
	if d > 2*time.Second {
		d = 2 * time.Second
	}
	time.Sleep(d)
}

func atomicWriteFile(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".tmp-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	// Ensure cleanup on any failure path.
	defer func() { _ = os.Remove(tmpName) }()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		return err
	}
	return nil
}

func writeJSON(path string, v any) error {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return atomicWriteFile(path, data, 0o644)
}

func writeNOTICE(path string, meta sourceMeta) error {
	content := fmt.Sprintf(`Dictionary files are derived from OpenCC (https://github.com/%s),
licensed under Apache License 2.0.

Normalized sources:
- TSCharacters.txt / TSPhrases.txt (traditional -> simplified)
- TWPhrasesRev.txt (Taiwan phrases toward simplified)
- TWVariants.txt / HKVariants.txt (regional glyphs reversed toward simplified)

When an entry has multiple candidates, the first candidate is kept.

Pinned upstream:
- ref: %s
- commit: %s
- commit_url: %s
- generated_at: %s

Regenerate with:
  go run ./scripts/gendict
  # or
  ./scripts/sync-dict.sh
`, meta.Repo, meta.Ref, meta.Commit, meta.CommitURL, meta.GeneratedAt)
	return atomicWriteFile(path, []byte(content), 0o644)
}

func shortSHA(sha string) string {
	if len(sha) > 12 {
		return sha[:12]
	}
	return sha
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

// sha256Prefix returns the first n bytes of SHA-256.
func sha256Prefix(data []byte, n int) []byte {
	sum := sha256.Sum256(data)
	if n > len(sum) {
		n = len(sum)
	}
	return sum[:n]
}
